### ISSUE TITLE
Use concise character class syntax '\d' instead of '0-9'

### ISSUE THREAD

**Issue by migui3230** [migui3230/SWE2-Project#1]
frontend/src/serviceWorker.js line 19

**Comment by migui3230** [comment]
![image](https://user-images.githubusercontent.com/74937076/229377527-f9fc1ead-a825-45dc-9f77-0bc1ba37b9bc.png)

**Comment by mquan1409** [comment]
This is a false positive issue because '/d' will match all the unicode digits when '[0-9]' will only match digits from 0-9. We are checking whether the host is localhost, so we should only check [0-9]
